-- MySQL Script generated by MySQL Workbench
-- Sun May  3 13:38:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ville` (
  `idville` INT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NULL,
  `distance` INT NULL,
  PRIMARY KEY (`idville`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marchand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marchand` (
  `idmarchand` INT NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NOT NULL,
  `localisation` MEDIUMTEXT NOT NULL,
  `ville_idville` INT NOT NULL,
  PRIMARY KEY (`idmarchand`, `ville_idville`),
  INDEX `fk_marchand_ville1_idx` (`ville_idville` ASC) VISIBLE,
  CONSTRAINT `fk_marchand_ville1`
    FOREIGN KEY (`ville_idville`)
    REFERENCES `mydb`.`ville` (`idville`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ressources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ressources` (
  `idressources` INT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idressources`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marchand_has_ressources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marchand_has_ressources` (
  `marchand_idmarchand` INT NOT NULL,
  `ressources_idressources` INT NOT NULL,
  PRIMARY KEY (`marchand_idmarchand`, `ressources_idressources`),
  INDEX `fk_marchand_has_ressources_ressources1_idx` (`ressources_idressources` ASC) VISIBLE,
  INDEX `fk_marchand_has_ressources_marchand_idx` (`marchand_idmarchand` ASC) VISIBLE,
  CONSTRAINT `fk_marchand_has_ressources_marchand`
    FOREIGN KEY (`marchand_idmarchand`)
    REFERENCES `mydb`.`marchand` (`idmarchand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marchand_has_ressources_ressources1`
    FOREIGN KEY (`ressources_idressources`)
    REFERENCES `mydb`.`ressources` (`idressources`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
